/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crylog_quinn4android_Quinn4Android */

#ifndef _Included_com_crylog_quinn4android_Quinn4Android
#define _Included_com_crylog_quinn4android_Quinn4Android
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crylog_quinn4android_Quinn4Android
 * Method:    Client_Insecure
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crylog_quinn4android_Quinn4Android_Client_1Insecure
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_crylog_quinn4android_Quinn4Android
 * Method:    Server_Insecure
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_crylog_quinn4android_Quinn4Android_Server_1Insecure
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
